---
title: "thresholdTMLE"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
devtools::document()
```


```{r}

#rmultinom(n = 2, c(1,2,3,4,5), rep(1/5,5))
rmults <- function(n, size, prob) {
  size = size[1]
  prob = prob[1]
  apply(rmultinom(n = n, 1:size, rep(prob, size))==1, 2, which)

}
rmults(2, c(5,5), c(1/5,1/5))
```

```{r}


library(simcausal)
D <- DAG.empty()
D <- D +
  node("W1", distr = "rmults", size = 15 , prob = 1/15) +
  node("W", distr = "rconst", const = W1 + 1) +
  node("S", distr = "runif",  min = -5, max = 5) +
  node("Y", distr = "rbinom", size =1 , prob = plogis((S ))) + 
    node("pY", distr = "rconst",const = plogis((S )))


setD <- set.DAG(D)
dat <- sim(setD, n = 1500)
dat

```

```{r}
findInterval(1.6,c(1,2,3))

```



```{r}
data <- as.data.table(dat)


```

```{r}

npsem <- list(define_node("W", "W", c()),
              define_node("A", "A", c("W")),
               define_node("v", "v", c(), time = unique(data$t)),
              define_node("Y", "Y", c("A", "W", "v"), time = unique(data$t))
              )
task <- tmle3_Task$new(data, npsem, id = "id", time = "t" )
```


```{r}
task$get_regression_task("Y")$data
```


```{r}
cutoffs <- quantile(dat$S, seq(0.05,1,length.out=15))
dat
tsk <- sl3_Task$new(dat, covariates = "W", outcome = "S")
lrnr <- Lrnr_CDF$new(make_learner(Lrnr_glm, family = binomial()), 10, cutoffs)


lrnr <- lrnr$train(tsk)
data.table(lrnr$predict(tsk))
```


```{r}
dat
tsk <- sl3_Task$new(dat, covariates = c("W", "S"), outcome = "Y")

lrnr <- Lrnr_thresh$new(make_learner(Lrnr_glm, family = binomial()), "S", cutoffs =cutoffs )

lrnr <- lrnr$train(tsk)
as.data.table(matrix(lrnr$predict(tsk), nrow = 2000))
```

```{r}
dat
cutoffs <- quantile(dat$S, seq(0.1,.9,length.out=8))
npsem <- list(define_node("W", "W", c()),
              define_node("S", "S", c("W")),
              define_node("Y", "Y", c("S", "W"))
              )
task <- tmle3_Task$new(dat, npsem)
task$data
factor_list <- list(LF_emp$new("W"), LF_fit$new("S", Lrnr_CDF$new(make_learner(Lrnr_hal9001, family = "binomial"), 10, cutoffs), type = "mean"), LF_fit$new("Y", Lrnr_thresh$new(make_learner(Lrnr_hal9001, family = "binomial"), "S", cutoffs =cutoffs ), type = "mean"))
likelihood <- Likelihood$new(factor_list)
likelihood <- likelihood$train(task)
```

```{r}
tlik <- Targeted_Likelihood$new(likelihood)
param <- Param_thresh$new(tlik, cutoffs)
as.data.table(param$clever_covariates(task)$Y)
lapply(param$estimates(task), as.data.table)
```

```{r}
mean(dat$Y[dat$S >= -3.96407782	])

```
```{r}
out <- param$estimates(task)
out$psi
colMeans(out$IC)

summary_from_estimates(task, list(out), simultaneous_ci = F , param_types = "threshold", param_names = as.vector(cutoffs))
```

```{r}

tlik$updater$update_step(tlik, task)
lapply(param$estimates(task), as.data.table)
```


```{r}
spec <- tmle3_Spec_Threshold$new()
dat
```

```{r}
task <- spec$make_tmle_task(dat, list("W" = "W", "A" = "S", "Y" = "Y"))
task$get_regression_task("A")$data
task$get_regression_task("Y")$data
lik <- spec$make_initial_likelihood(task, list("A" = make_learner(Lrnr_glm, family = binomial()), "Y" = make_learner(Lrnr_glm, family = binomial())))
updater <- spec$make_updater()
tlik <- spec$make_targeted_likelihood(lik, updater)
spec$make_params(task, tlik)
```

```{r}

tlik$updater$set_estimates(task)
tlik$updater$update_step(tlik, task)
```


```{r}

task$get_regression_task("Y")
```


```{r}
param <- tlik$updater$tmle_params[[1]]
est <- (param$estimates(task))
colMeans(est$IC)
est$psi
```




