---
title: "WAY_gradient_projection"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

devtools::document()
```


```{r}
library(simcausal)
library(sl3)
library(tmle3)
findInterval(1, seq(0,100,3))
# Generate long format data
D <- DAG.empty()
D <- D +
  node("L0", distr = "rbinom",  size = 1, prob = 0.5) +
  
  node("A0", distr = "rbinom", size = 1, prob =plogis( 0.4 + L0/300) ) +
  node("L1", distr = "rbinom", size = 1, prob = plogis( 0.4 + A0/3 -L0/300 )) +
  node("A1", distr = "rbinom", size = 1, prob =plogis( 0.2 + L0/200 - A0/3 + L1/300) ) +
  node("Y",  distr =  "rbinom", size = 1, prob = plogis(0.2 + L0/200 + A1/3 - A0/5 + L1/300) ) 
 

setD <- set.DAG(D)
dat <- sim(setD, n = 30000)
dat$id <- dat$ID
dat$ID <- NULL
dat
dat$L0 <- seq(0,100,4)[findInterval(dat$L0, seq(0,100,5))]
dat

npsem <- list(define_node("L0", "L0"),
              define_node("A0", "A0", "L0"),
              define_node("L1", "L1", c("L0", "A0")),
              define_node("A1", "A1", c("L0", "A0", "L1")),
              define_node("Y", "Y", c("L0", "A0", "L1", "A1")))

task <- tmle3_Task$new(dat, npsem)
task$data
lrnr_glm <- make_learner(Lrnr_glm)
factor_list <- list(LF_emp$new("L0"),
                    LF_fit$new("A0", lrnr_glm),
                    LF_fit$new("L1", lrnr_glm),
                    LF_fit$new("A1", lrnr_glm),
                    LF_fit$new("Y", lrnr_glm))
likelihood <- Likelihood$new(factor_list)
likelihood$train(task)
```

```{r}
ipw2 <- function(A0, A1, Y, L1, L0, gA0, gL1, gA1){
  if(F) {return(A0*A1*Y/(gA0*gL1*gA1) )}
  # true ipw
  gA0 = plogis( 0.4 + L0/300)
  gL1 = plogis( 0.4 + A0/3 -L0/300 )
  gA1 = plogis( 0.2 + L0/200 - A0/3 + L1/300)
  return(A0*A1*Y/(gA0*gL1*gA1))
}

generator2 <-function(tmle_task, lik = NULL, target_param = NULL, node, outcome = T){
  task <- tmle_task$get_regression_task(node)
  # TODO make sure get_tmle_node ids match regression ids
  A0 <- tmle_task$get_tmle_node("A0", format = T)[[1]]
  A1 <- tmle_task$get_tmle_node("A1", format = T)[[1]]
  L0 <- tmle_task$get_tmle_node("L0", format = T)[[1]]
  L1 <- tmle_task$get_tmle_node("L1", format = T)[[1]]
  Y <- tmle_task$get_tmle_node("Y", format = T)[[1]]
  


  

  IC <- ipw2(A0, A1, Y, L1, L0, gA0 = NULL, gL1 = NULL, gA1 = NULL)
 
  cols <- task$add_columns(data.table(IC = IC))
  task <- task$clone()
  nodes <- task$nodes
  nodes$outcome <- "IC"
  nodes$covariates <- c(nodes$covariates, node)
  task$initialize(
        task$internal_data,
        nodes = nodes,
        folds = task$folds,
        column_names = cols,
        row_index = task$row_index,
        outcome_type = "continuous"
      )
  return(task)
  # task$next_in_chain(column_names = cols, covariates  = c(task$nodes$covariates, task$nodes$outcome), outcome = "IC")
}

grad <- Gradient$new(likelihood, generator2, list(update_nodes = c("Y", "L1")))
f<-grad$train(task)
```

```{r}

res <- lapply(grad$compute_component(task, "Y1"), as.data.table)
res$EIC

A0 <- task$get_tmle_node("A0", format = T)[[1]]
  A1 <- task$get_tmle_node("A1", format = T)[[1]]
  L0 <- task$get_tmle_node("L0", format = T)[[1]]
  L1 <- task$get_tmle_node("L1", format = T)[[1]]
  Y <- task$get_tmle_node("Y", format = T)[[1]]
EY <- plogis(0.2 + L0/200 + A1/3 - A0/5 + L1/300)

gA0 = plogis( 0.4 + L0/300)
  gL1 = plogis( 0.4 + A0/3 -L0/300 )
  gA1 = plogis( 0.2 + L0/200 - A0/3 + L1/300)
  
trueEIC <- (A0*A1/gA0 / gL1/ gA1)*(Y - EY)

cbind(trueEIC, res$EIC)
```



```{r}

ressq<- (trueEIC - res$EIC[[1]])^2
mean(ressq)
```




```{r}
library(simcausal)
library(sl3)
library(tmle3)

# Generate long format data
D <- DAG.empty()
D <- D +
  node("W1", distr = "runif", min = 0, max = 100) +
  node("W", distr = "rconst", const = round(W1)) +
  node("A", distr = "rbinom", size = 1, prob =plogis( 0.4 + W/300) ) +
  node("Y",  distr =  "rbinom", size = 1, prob = plogis(0.4 + A/4 - W/300) ) 
 

setD <- set.DAG(D)
dat <- sim(setD, n = 3000)
dat$id <- dat$ID
dat$ID <- NULL
dat

sum(dat$A * dat$Y)
sum((1-dat$A) * dat$Y)
```

```{r}
paste0(1:3, 1:3)

```


```{r}
npsem <- list(define_node("W", "W", variable_type = variable_type("continuous")), 
              define_node("A", "A", "W"),
               define_node("Y", "Y", c("A", "W")))

task <- tmle3_Task$new(dat, npsem)
task$get_tmle_node("W", format = T)
factor_list <- list(LF_emp$new("W"), 
                    LF_fit$new("A", make_learner(Lrnr_glm)),
                     LF_fit$new("Y", make_learner(Lrnr_glm)))

lik <- Likelihood$new(factor_list)
lik<-lik$train(task)
```


```{r}
type = "both"
ipw <- function(Y, A, g, W){
  if(type == 1){
      return(Y*A/(plogis(0.4+W/300)) )
  } else if (type == 0){
    return(Y*(1-A)/(1-plogis(0.4 + W/300)))
  }
  Y*A/(plogis(0.4 + W/300))  - Y*(1-A)/(1-plogis(0.4 + W/300))
}
generator <-function(tmle_task, lik = NULL, target_param = NULL, node, outcome = T){
  task <- tmle_task$get_regression_task(node)
  A <- task$X$A
  Y <- task$Y
  W <- task$X$W

  g <- lik$get_likelihood(tmle_task, "A")

  IC <- ipw(Y,A,g, W)
 
  cols <- task$add_columns(data.table(IC = IC))
  task <- task$clone()
  nodes <- task$nodes
  nodes$outcome <- "IC"
  nodes$covariates <- c(nodes$covariates, node)
  task$initialize(
        task$internal_data,
        nodes = nodes,
        folds = task$folds,
        column_names = cols,
        row_index = task$row_index,
        outcome_type = "continuous"
      )
  return(task)
  # task$next_in_chain(column_names = cols, covariates  = c(task$nodes$covariates, task$nodes$outcome), outcome = "IC")
}


grad <- Gradient$new(lik)

#grad$expand_task(task, "Y")$data

f=grad$train(task)
```


```{r}
gen_task <- generator(task, grad$likelihood, node = "Y")
ipw_pred <- grad$fit_object[[1]]$predict(gen_task)
ipws <- gen_task$Y

keep <- (ipws < 0)
plot( ipws[keep], ipw_pred[keep])

keep <- (ipws > 0)
plot( ipws[keep], ipw_pred[keep])

residual <- ipw_pred - ipws
mean(residual^2)
mean(residual^2)
```



```{r}
pY = lik$get_likelihood(task, "Y")
#pA = lik$get_likelihood(task, "A")

A = task$get_tmle_node("A")
W = task$get_tmle_node("W")
Y = task$get_tmle_node("Y")
EY = plogis(0.4 + A/4 - W/300 )

pA = plogis(0.4 + W/300)
EIC1 = (A/pA)*(Y - EY)

pA = 1 - plogis(0.4 + W/300)
EIC0 = ((1-A)/pA)*(Y - EY)




#EY = Y * (pY) + (1-Y)* (1-pY)
EY = plogis(0.4 + A/4 - W/300 )


EIC = EIC1 - EIC0


data <- grad$compute_component(task, "Y")

true <- lapply(list(data$EIC), as.data.table)[[1]]
truemat = cbind(true, EIC)
truemat[[1]] <- (sapply(truemat[[1]], format, scientific = F))
truemat
keep <- truemat[[2]]!=0
sqrt(mean((as.numeric(truemat[[1]][keep]) - truemat[[2]][keep])^2))
```

```{r}
longtask <- grad$expand_task(task, "Y")
longtask$data
longtask <- grad$expand_task(longtask, "Y")
longtask$data
lapply(grad$compute_component(longtask, "Y"), as.data.table)
```





